// sample-vue/src/components/Todo.vue
<template>
  <div>
    <input type="checkbox" @click="handleClickCheckbox" />
    <span v-bind:class="{completed: todo.completed}">{{todo.title}}</span>
    <button @click="handleClickDeleteButton">削除</button>
  </div>
</template>

<script lang="ts">
import { Component, Vue, Emit, Prop } from "vue-property-decorator";
import { ITodo } from "../ITodo";
@Component
export default class Todo extends Vue {
  @Prop({ type: Object, required: true })
  private todo!: ITodo;

  private handleClickDeleteButton() {
    this.todo.deleted = true;
  }

  private handleClickCheckbox() {
    this.todo.completed = !this.todo.completed;
  }
}
</script>

<style scoped>
.completed {
  text-decoration: line-through;
}
</style>

// sample-angular/src/app/todo/todo.component.ts
import { Component, OnInit, Input, Output } from '@angular/core';
import { ITodo } from '../ITodo';
import { EventEmitter } from 'protractor';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent implements OnInit {
  @Input() todo: ITodo;
  constructor() { }

  ngOnInit(): void {
  }

  handleClickDeleteButton() {
    this.todo.deleted = true;
  }

  handleClickCheckbox() {
    this.todo.completed = !this.todo.completed;
  }
}

<input type="checkbox" (click)="handleClickCheckbox()">
<span [class.completed]="todo.completed">{{todo.title}}</span>
<button (click)="handleClickDeleteButton()">削除</button>
